config/routes.rb
Rails.application.routes.draw do
  
  
  root             'static_pages#home'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete  'delete' => 'users#destroy'
  get 'logout'  => 'sessions#destroy'

  get 'game'   => 'static_pages#game'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts, dependent: :destroy
	attr_accessor :remember_token
	before_save   :downcase_email
	
	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password 
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	  end

	  # Возвращает случайный токен
  def User.new_token
    SecureRandom.urlsafe_base64
  end

 # Забывает пользователя
 def forget
    update_attribute(:remember_digest, nil)
  end

   # Запоминает пользователя в базе данных для использования в постоянной сессии.
   def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

    # Возвращает true, если предоставленный токен совпадает с дайджестом.
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	  end

	  def feed
		Micropost.where("user_id = ?", id)
	  end

	    # Переводит адрес электронной почты в нижний регистр.
		def downcase_email
			self.email = email.downcase
		  end
	  
		  # Создает и присваивает активационнй токен и дайджест.
		  def create_activation_digest
			self.activation_token  = User.new_token
			self.activation_digest = User.digest(activation_token)
		  end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	def logged_in_user
		unless logged_in?
		  store_location
		  flash[:danger] = "Please log in."
		  redirect_to login_url
		end
	  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy

    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
          flash[:success] = "Micropost created!"
          redirect_to root_url
        else
            @feed_items = []
          render 'static_pages/home'
        end
    end
  
    def destroy
        
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end


    private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     log_in user
     params[:session][:remember_me] == '1' ? remember(user) : forget(user)
     redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Не совсем верно!
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end

  def help
  end

  def contact
  end

  def game
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def new
    @user = User.new
  end

  def destroy
   if User.destroy(params[:id])
    flash[:success] = "User deleted!"
    @users = User.paginate(page: params[:page])
    redirect_to users_url
   else
    redirect_to root_url
   end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create 
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome my friend!"
        redirect_to @user
      else
        render 'new'

      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation)
  end


  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	  # Осуществляет вход данного пользователя.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Запоминает пользователя в постоянную сессию.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Возвращает true, если заданный пользователь является текущим.
  def current_user?(user)
    user == current_user
  end

   # Перенаправляет к сохраненному расположению (или по умолчанию).
   def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Сохраняет запрошенный URL.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  # Возвращает текущего вошедшего пользователя (если есть).
  def current_user
      if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

   # Возвращает true, если пользователь вошел, иначе false.
  def logged_in?
    !current_user.nil?
  end

    # Осуществляет выход текущего пользователя.
    def log_out
      forget(current_user)
      session.delete(:user_id)
      @current_user = nil
    end

    # Забывает постоянную сессии.
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	# Возвращает граватар для данного пользователя
  def gravatar_for(user, options = { size: 80 })
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.name, class: "gravatar")
end
end

app/views/layouts/_footer.erb
<footer class="footer navbar navbar-inverse">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_gmenu.erb
<div class="dropdown">
<button class="mainmenubtn">Главное меню</button>
<div class="dropdown-child">
  <a href="http://www.вашдомен.ru/page1.html">Подраздел 1</a>
  <a href="http://www.вашдомен.ru/page2.html">Подраздел 2</a>
  <a href="http://www.вашдомен.ru/page3.html">Подраздел 3</a>
  <a href="http://www.вашдомен.ru/page4.html">Подраздел 4</a>
  <a href="http://www.вашдомен.ru/page5.html">Подраздел 5</a>
</div>
</div>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  
    <%= link_to "sample app", root_path, id: "logo" %>
   
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users",  users_path %></li>
          <div class="dropdown">
            <button class="mainmenubtn">Главное меню</button>
            <div class="dropdown-child">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><a id="cool", href="http://www.вашдомен.ru/page5.html">Подраздел 5</a></li>
          <% end %>
             
            </div>
          </div>
 
        
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/_shim.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
     <title><%= full_title(yield(:title)) %></title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="header">
      <%= render 'layouts/header' %>
    </div>
    
     <div class="loh">      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

            <section class=" sonya container">
                <%= yield %>        
            </section>   
              <div class="image">
                  <%= link_to image_tag("rails1.png", alt: "Rails logo"),
                  'http://rubyonrails.org/' %>
              </div>
      </div>

    <div class="footer">
       <%= render 'layouts/footer' %> 
    </div>
<%= debug(params) if Rails.env.development? %>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
  <%= micropost.content %>
  <%= cl_image_tag("#{micropost.picture}", :width => 300, :height => 200, :crop => :fill, :cloud_name => "elcaronossam") if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
        <%= button_to 'Destroy', micropost, method: :delete, :onclick => "return confirm('Are you sure?')" %>
    <% end %>
    </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
    <span class="picture">
    <%= f.file_field :picture %>
  </span>
    <% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help </h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/home.html.erb
<% provide(:title) %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1 id="cool" >Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/static_pages/index.html.erb
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body class="body">
    <style>
        .body{
        background-color: rgb(255, 0, 0)
        }
        .obj{
          
        }
    </style>
    <canvas id="IL" width="1050" height="1050" class="obj">
    <script>
       class MovingObject {
            constructor(x0,y0,vx0,vy0){
                this.x = x0;
                this.y = y0;
                this.vx = vx0;
                this.vy = vy0;
            }
            draw(){
                ctx.strokeRect(this.x-10,this.y-10,50,50);
            }
            move(){
                this.x += this.vx;
                this.y += this.vy;
            }
            CheckReflection(){
                if(this.x > 800){
                    this.x = 800
                    this.vx = -this.vx}
            if(this.y > 600){
                this.y = 600
                this.vy = -this.vy
            }
            if(this.x < 0){
                this.x = 0
                this.vx = -this.vx}
            if(this.y < 0){
                this.y = 0
                this.vy = -this.vy
            }
            }
       }

            class ColoredMovingObject extends MovingObject{
                constructor(x0, y0, vx0, vy0, color){
                    super(x0, y0, vx0, vy0)
                    this.color = color;
                }
                draw(){
                    ctx.strokeStyle = this.color;
                    ctx.strokeRect(this.x-10,this.y-10,50,50);
            }
        }

        class Moving extends ColoredMovingObject{
            constructor(x0, y0, vx0, vy0, color){
                    super(x0, y0, vx0, vy0, color);
                    this.size = 10;
                    this.sizeChange = 0.1*Math.random();
                    this.maxSize = 50;
        }
        draw(){
                    ctx.strokeStyle = this.color;
                    ctx.strokeRect(this.x-this.size,
                                    this.y-this.size,
                                    2*this.size,
                                    2*this.size);
            }
            move(){
                super.move()
                this.size+=this.sizeChange;
                if (this.size>this.maxSize){
                    this.size = this.maxSize;
                    this.sizeChange=-this.sizeChange;
                }

                if (this.size<0){
                    this.size = 0;
                    this.sizeChange=-this.sizeChange;
                }
            }
    }
       console.log("obj")
       var canvas = document.getElementById("IL");
       var ctx = canvas.getContext("2d");

       var squares = [];
        for (var i=0; i<160; i++){
            var square = new Moving(
                Math.random()*800,
                Math.random()*400,
                Math.random()*20-10,
                Math.random()*20-10,
                "#"+Math.floor((0xffffff*Math.random())).toString(16)
                );
            squares.push(square)
            }

       
        function DrawStep(){
            for(let i=0;i<squares.length;i++){
                let square = squares[i]
            
            square.draw();
            square.move();
            square.CheckReflection()
            }
        }
        
    
        
        setInterval(DrawStep,3);
    </script>

    </body>
    

</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
 | <%= button_to 'Destroy', user, method: :delete, :onclick => "return confirm('Are you sure you want to delete this user?')" %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
 
    <%= render @users %>
  
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>